[build]
  command = "npm ci && ./node_modules/.bin/nx build destinations --configuration=production"
  publish = "dist/apps/destinations"

[build.environment]
  NODE_ENV = "production"
  NX_IGNORE_UNSUPPORTED_TS_SETUP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200