[build]
  command = "npm exec nx build homepage -- --configuration=production"
  publish = "../../dist/apps/homepage"

[build.environment]
  NODE_ENV = "production"
  NX_IGNORE_UNSUPPORTED_TS_SETUP = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
