[build]
command = "npm ci --include=dev && npm run build:destinations"
  publish = "dist/apps/destinations"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"